# Generated by Django 5.2.6 on 2025-10-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainrot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brainrotitem',
            name='img',
            field=models.ImageField(upload_to='brainrot_images/'),
        ),
    ]
